### ISSUE TITLE
Support ruby3 + rails 6

### ISSUE THREAD

**Issue by encoreshao** [encoreshao/china_regions#10]
```
❯ rake china_regions:all

rake aborted!
ArgumentError: You tried to define a scope named "filter" on the model "Province", but ActiveRecord::Relation already defined an instance method with the same name.
/Users/encore/Dev/Github/soap-api/app/models/province.rb:15:in `<class:Province>'
/Users/encore/Dev/Github/soap-api/app/models/province.rb:4:in `<main>'
Tasks: TOP => china_regions:import
(See full trace by running task with --trace)
```

**Comment by encoreshao** [comment]
update method filter to filter_by in Province
